### ISSUE TITLE
dfx install will take the canister WASM that's the output of a custom tool

### ISSUE THREAD

**Issue by hansl** [dfinity/sdk#1107]
It has a private copy, and should use that. When multiple canisters share the same WASM, and the WASM changes between the builds, `dfx deploy` will build all canisters, then install them, but because it uses the output of the build tool (and not its private copy in `.dfx/local`), it will install the same WASM in all three canisters (which is the wasm that was last built).

**Comment by sesi200** [comment]
supported by now
