### ISSUE TITLE
As a developer, I can use the IC to host my react app, so I can share it with my friends and recruit feedback/collaborators

### ISSUE THREAD

**Issue by gobengo** [dfinity/sdk#1114]
User Context:
* I just finished a tutorial like https://create-react-app.dev
* I can't believe I just coded a real app! I wonder what my friends will say...
* Wait, how do I even share this with them?...
* Uhhhh https://create-react-app.dev/docs/deployment

Value Proposition:
* The Internet Computer is a place you can deploy your react apps so you can share them with your friends.

Differentiator:
* Unlike _______
  * Netlify
    * The IC isn't powered by one startup that will change the price when they get bigger, or shut down when they sell out
  * AWS (S3 + Cloudfront)
    * It's not way too complicated, it's easy!
  * next.js (now vercel.com)
    * generic critiques of VC-backed startups, centralized architectures.
    * Hard to differentiate on DX quite yet as their is quite good for this use case. We need to match this for devs who are savvy enough to know these alternatives, but the beauty is most people in this persona won't already know about vercel.com.

Acceptance Criteria:
* I can read documentation on how to port a fresh create-react-app app to be compatible with `dfx deploy`, and when I follow the instructions, I now have a URL to share with my friends!

**Comment by sesi200** [comment]
React support is in the works
