### ISSUE TITLE
As a canister author, my canister can expose a WebSocket API that any ws client can connect to, so I can implement existing WS APIs and access my canister's functionality from existing ws clients

### ISSUE THREAD

**Issue by gobengo** [dfinity/sdk#1122]
Use Cases:
* Write a canister backend that implements graphql-ws
  * Who? [@lastmjs](https://twitter.com/lastmjs/status/1316116363287519233)
    > They would need to provide us with web socket support of some kind, otherwise you'd have to poll. I've brought up web sockets multiple times, we'll see what happens with that
* Write a canister backend that implements JSON-RPC over WebSocket: https://besu.hyperledger.org/en/1.2.1/Pantheon-API/Using-JSON-RPC-API/
  * I believe the main ethereum daemon is invoked over JSON-RPC?

Blocked By:
* ?

Context:
* bidirectional socket abstractions are quite different than the 'request-response' RPC that seems to be how most canisters are invoked now. But there is some prior art on emulating the former on top of the latter. https://pushpin.org/docs/protocols/websocket-over-http/

**Comment by sesi200** [comment]
Not part of SDK, discussion is happening here: https://forum.dfinity.org/t/websockets-on-the-ic-psychedelicdao/14817
