### ISSUE TITLE
follow up items for update to clap3

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1178]
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522458807
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522464440
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522465980
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522466360
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522470693
- [ ] https://github.com/dfinity/sdk/pull/1145#discussion_r522472727

**Comment by sesi200** [comment]
all tasks completed
