### ISSUE TITLE
bootstrap-js localforage has DOMException (indexedDB) in Firefox Private Browsing mode

### ISSUE THREAD

**Issue by gobengo** [dfinity/sdk#1227]
Steps to Reproduce:
* Follow the release docs for sdk main branch. https://github.com/dfinity/sdk/blob/master/docs/process/release.adoc
* when it comes to testing the `$hello_world_assets_url` (asset canister), use Firefox in Private Browsing mode

Expected Behavior
* Asset canister behaves same as chrome + firefox in not-incognito mode

Actual Behavior
(originally [in notion](https://www.notion.so/2020-12-01-5a227506c3f04f359cc11613ba7ef43b#7e3bb63ce8fd4ace9b67a3976c47a7d8))
- 12:26pm - new rc hello_world asset canister works in chrome, but not firefox

    ```jsx
    Error

    Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. bootstrap-e4bcb8b2c131b80f949b.js:2:513237
        <anonymous> http://localhost:8000/bootstrap-e4bcb8b2c131b80f949b.js:2
        (Async: promise callback)
        <anonymous> http://localhost:8000/bootstrap-e4bcb8b2c131b80f949b.js:2
        r http://localhost:8000/bootstrap-e4bcb8b2c131b80f949b.js:2
        <anonymous> http://localhost:8000/bootstrap-e4bcb8b2c131b80f949b.js:2
        <anonymous> http://localhost:8000/bootstrap-e4bcb8b2c131b80f949b.js:2
    ```

    - code from debugging 
    (with source maps, I can tell 'this' = 'localforage' in bootstrap.js site.ts:191

    ```jsx
    async getOrCreateUserIdentity() {
    let e = awaitf('userIdentity', 'dfinity-ic-user-identity');
    // ERROR HERE
    // when awaiting the promise returned from this.retrieve(...)
    if (void 0 === e && (e = await this.retrieve('dfinity-ic-user-identity')), e) return u.Ed25519KeyIdentity.fromJSON(e);
    {
    const e = u.Ed25519KeyIdentity.generate();
    return awaitthis.store('dfinity-ic-user-identity', JSON.stringify(e)),
    e
    }
    }
    ```

Diagnosis:
* I think this might just be a bug or edge case in `localforage`, as used by bootstrap.js (or maybe its dep on agent). https://github.com/jakearchibald/idb/issues/81
* localforage is trying to use the browser's IndexedDB APIs, which are probably blocked in Firefox Private Browsing.

Change Request:
* In Firefox private browsing, bootstrap.js should not try to use IndexedDB. Instead, just use regular localStorage? (if localforage isn't capable of sniffing out what will work, we can try to catch this error ourself and re-initialize localforage in a way that wont hit it)

**Comment by sesi200** [comment]
No reports of such issues in 1y+, closing as likely fixed. Please reopen if issue reappears.
