### ISSUE TITLE
Developer can be periodically prompted to update DFX

### ISSUE THREAD

**Issue by ghost** [dfinity/sdk#1280]
**Story**

### "As a developer I want to be periodically prompted to update DFX if there's a newer version so that I don't have to remember to check for updates myself."

**Demo**

1. Use DFX for the first time during a set period (daily, weekly, monthly)
2. Be told if there's a newer version of DFX available
3. ~~Be prompted to automatically update `[Y] / N`~~

**Design**

TBD

**Comment by sesi200** [comment]
Moving into [SDK-759](https://dfinity.atlassian.net/browse/SDK-759) as this is a maintenance task
