### ISSUE TITLE
Developers can add an "interface" canister type for canisters they don't have wasm (e.g. already deployed)

### ISSUE THREAD

**Issue by hansl** [dfinity/sdk#1302]
Currently, people are creating bogus `custom` canisters, but it would be better to have a dedicated type that is semantically closer to what people want/expect.

It should probably have a DID field and a canister ID field. The canister ID should have a network map.

Something like this:

```json
{
  "type": "interface",
  "did": "some/path/to/file.did",
  "canisterId": {
    "local": "abcde-fghij-aa",
    "ic": "...",
  }
}  
```

The difficulty of this feature is in the mapping to canister ID, which until now we always understood to be in the `canister_ids.json` file. A potential solution would be to write the same map of canister ID in the file on build.

This new canister type is a no-op for building and installing.

**Comment by sesi200** [comment]
Implemented a while ago as 'remote canister'
