### ISSUE TITLE
sdk install script upkeep

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1352]
Clean up and document the install script. Know that this script is read by developers just like any other piece of code. It should be well documented, and give the user confidence in what they are about to install.

>I download the script and give it a quick review, to make sure it’s not doing anything obviously wrong.

>I am tickled to see this comment in the headers:

`# Borrowed from rustup (https://sh.rustup.rs)`

>as I wrote most of rustup’s install script. I also know smart people have carefully improved it over time — it is a very battle-tested piece of tricky shell script. That gives me some immediate confidence in this script. There is though a lot of Dfinity-specific code here, and it is not as lovingly-maintained as rustup’s, with bizarre spacing and stripped comments (it looks like it has been machine-processed). Important functionality like architecture detection, platform-specific quirk handling, and the security-sensitive curl configuration are borrowed straight from rustup though.

>I don’t see anything obviously incorrect in the script, though its poor readability gives me pause — this is a script some hackers will definitely read before running, and it needs to give them confidence.

**Comment by sesi200** [comment]
Moving into [SDK-758](https://dfinity.atlassian.net/browse/SDK-758) as this is a maintenance task
