### ISSUE TITLE
The uninstall script should report to the user what it is doing.

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1354]
>I read the uninstall script and I don’t see any obviously catastrophic bugs. It does mention a DFX_INSTALLATION_ROOT environment variable that I don’t yet know anything about.

>I run the uninstall script. It works, though provides no feedback.

**Comment by sesi200** [comment]
Moving to [SDK-757](https://dfinity.atlassian.net/browse/SDK-757) as this is a maintenance task
