### ISSUE TITLE
dfx not added to $PATH on Linux

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1355]
When installation completes, the user should be informed that they need to add dfx to their PATH if they are on Linux.

>dfx is not immediatly in my PATH. The install script or the docs could do a bit better in guiding the user here. I know from experience that this first step of getting PATH set correctly is a very common blocker for newbies. Unfortunately there are no perfect technical solutions to setting up PATH across all platforms, so informing the user about it has to be part of the install experience.

>I am on Linux. On Aimee’s Mac though dfx is immediately on the path. This is because the installer installed directly to /usr/local/bin. This creeps me out a bit as I am accustomed to needing to sudo to write to that location. Maybe it’s common on Macs to install directly to /usr/local/bin without permission. On Linux, my dfx is in ~/bin.

**Comment by sesi200** [comment]
Install script checks if install dir is in path.
