### ISSUE TITLE
Remove multiple prints of the dfinity logo welcome banner.

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1361]
>The final thing that is striking about this command is that it prints a massive welcome greeting: huge logo, links to docs, basic commands.

>This is perfectly fine for something on first run, but I don’t want to see this again. It’s obvious though that this is not something that happens only on first run, since we’ve seen this message multiple times.

**Comment by sesi200** [comment]
Only happens on `dfx new` now. Good enough.
