### ISSUE TITLE
Revisit the SDK version management

### ISSUE THREAD

**Issue by lwshang** [dfinity/sdk#1397]
Current SDK version management around `dfx cache` is feature uncompleted and the word "cache" is misleading.

Proposed improvements:
* Replace the `dfx cache` with `dfx toolchain`, subcommands may have different names/functionalities;
* `dfx toolchain install/uninstall` require semver as argument;
* No matter how SDK is installed (install.sh or package manager), there should always be a complete toolchain ready to use;

The new `dfx` installation procedure:
1. The latest complete toolchain will be installed to `~/.cache/dfinity/versions/a.b.c/`;
2. Soft link `~/.cache/dfinity/current/` to `~/.cache/dfinity/versions/a.b.c/`;
3. Soft link `/usr/local/bin/dfx` to `~/.cache/dfinity/current/dfx`;

The new `dfx` upgrade procedure:
1. The latest complete toolchain will be installed to `~/.cache/dfinity/versions/x.y.z/`;
2. Soft link `~/.cache/dfinity/current/` will point to `~/.cache/dfinity/versions/x.y.z/`;

**Comment by sesi200** [comment]
Closing as outdated. If still relevant, @lwshang please re-create as a Jira ticket.
