### ISSUE TITLE
Revisit the --no-wallet option

### ISSUE THREAD

**Issue by lsgunnlsgunn** [dfinity/sdk#1579]
This option is really confusing--at least three or four people have stumbled over this already.

One possible approach would be to change the default to make the wallet a controller by default. People could then choose to remove it from the controller list or run with `--no-wallet` to explicitly run commands using their current identity. This would also address the related issue https://github.com/dfinity/wallet-rs/issues/66.

Another possibility might be to change the name of the option to something like `--use-current-identity`.

**Comment by adamspofford-dfinity** [comment]
The flag was changed to only apply to canister creation, and canister creation changed to set both the caller and wallet as controllers. Is this still an issue?
