### ISSUE TITLE
Feat: Remove dependency on npm

### ISSUE THREAD

**Issue by krpeacock** [dfinity/sdk#1584]
As a user who wants to deploy static assets that do not involve the Node Package Manager, I want to be able to run `dfx deploy` without a dependency on node.

Acceptance criteria:

- should be able to add a canister with `"type": "assets"` and a `"source"` and deploy successfully without depending on node
- move `npm build` to an optional `"build"` config in `dfx.json`

**Comment by sesi200** [comment]
Handled in #2629
