### ISSUE TITLE
SDK for aarch64

### ISSUE THREAD

**Issue by timohanke** [dfinity/sdk#1651]
We need the SDK for users of M1-based Macs.

**Comment by nmattia** [comment]
Would be really, really nice to be able to build on aarch64. As far as I can tell the only issue currently is that we require released assets for the build. Looks like this is just a matter of `niv add`ing some the correct download URLs to `sources.json` and pinging whomever is responsible for `https://download.dfinity.systems/blessed/ic/<rev>/sdk-release/x86_64-darwin/<asset>` to populate it. Who do we reach out to to get some aarch64 builds of the f[ollowing binaries](https://github.com/dfinity/sdk/blob/856ff9243410bf25e62d1eaffb352c6294a30632/scripts/write-dfx-asset-sources.sh#L65)?

``` bash
"ic-ref" "icx-proxy" "ic-starter" "motoko" "replica" "canister-sandbox" "sandbox-launcher"
```
