### ISSUE TITLE
Deploy-Wallet should install to any canister

### ISSUE THREAD

**Issue by krpeacock** [dfinity/sdk#1723]
The situation this developer encountered shouldn't exist: https://forum.dfinity.org/t/403-forbidden-error-when-running-command-dfx-identity-network-ic-deploy-wallet-canister-identifer/5412/17

As a user, if my principal has permission to deploy to a canister, I expect that the deploy-wallet command will deploy cycles wallet wasm

**Comment by adamspofford-dfinity** [comment]
Fixed in #2156
