### ISSUE TITLE
npm start fails due to "options.forEach is not a function"

### ISSUE THREAD

**Issue by srsudar** [dfinity/sdk#1870]
Following [the quickstart instructions](https://smartcontracts.org/docs/quickstart/local-quickstart.html) I got the following error after running `npm start`:

```
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/Users/sudars/code/dfinity-start/hello/node_modules/webpack-cli/lib/webpack-cli.js:108:21)
<snip>
```

A [similar issue](https://github.com/webpack/webpack-cli/issues/2990) is noted on the `webpack-cli` repo. I managed to fix it by removing `node_modules/`, deleting `package-lock.json`, and changing the `webpack-cli` version in `package.json` to `4.9.0`:

```
  "webpack-cli": "4.9.0",
```

Reinstalling and rerunning `npm start` and then we're up and running. I'm not submitting a PR because I'm not sure of the other implications of revving that version.

**Comment by justinmchase** [comment]
Here is the issue in the source project:
https://github.com/webpack/webpack-cli/issues/2990

I can confirm bumping it to `4.9.0` appears to work

**Comment by krpeacock** [comment]
Sorry, hadn't checked this issue in a while. I'll get this fixed for the next dfx release
