### ISSUE TITLE
nix-shell: ERROR: Repository not found: git@github.com/dfinity-lab/common

### ISSUE THREAD

**Issue by J4NV5** [dfinity/sdk#1955]
https://github.com/dfinity/sdk/blob/master/nix/default.nix#L5-L11

This comment does not explain where to obtain the common repo, and the one it provides as a fallback does not exist:
git@github.com/dfinity-lab/common

**Comment by ggreif** [comment]
`dfinity-lab` contains repositories that aren't open-sourced yet.

**Comment by J4NV5** [comment]
well that's retarded. i guess i'm not using this blockchain

**Comment by paulyoung** [comment]
Can this issue be reopened? It's still not possible to get `nix-shell` to work as described in the contributing guidelines.

**Comment by paulyoung** [comment]
i.e. https://github.com/dfinity/sdk/blob/d10f20b18790718a07af9dbc8c5a9833ccb2b83e/.github/CONTRIBUTING.adoc

**Comment by paulyoung** [comment]
@ggreif I’m wondering if I can stub out the common repo using the mechanism below.

https://github.com/dfinity/sdk/blob/b0a8cc3557dc218779756464c67875d47c227183/nix/default.nix

**Comment by paulyoung** [comment]
I'm working around this on macOS with `nix-shell -p rustc cargo libiconv openssl_1_1 pkgconfig darwin.apple_sdk.frameworks.DiskArbitration darwin.apple_sdk.frameworks.Foundation` for now.
