### ISSUE TITLE
Provide a specification for dfx.json

### ISSUE THREAD

**Issue by nmattia** [dfinity/sdk#1963]
It would be great to have a spec for the `dfx.json`. I see it used in scripts here and there, would be nice to know exactly what goes into it!

**Comment by dansteren** [comment]
I would also like to see this. I'm able to find some examples of working dfx.json files in the examples repo: https://github.com/dfinity/examples. There's a rough explanation at https://smartcontracts.org/docs/rust-guide/rust-quickstart.html#_dfx_json. These are a good start but I'm looking for something more like NPM's Package.json documentation: https://docs.npmjs.com/cli/v6/configuring-npm/package-json. Ideally there would even be a [JSON schema](https://json-schema.org/).

For most projects the provided examples and existing documentation are likely enough but it would be nice to have a page explaining the nuances of each field.

**Comment by jason-icp** [comment]
related to https://github.com/dfinity/sdk/issues/661

**Comment by sesi200** [comment]
Handled in #2361. Please Open a new feature request in Discussions if this is not enough.
