### ISSUE TITLE
Dfx 0.9.0 gets stuck when trying to deploy canister with wrong identity 

### ISSUE THREAD

**Issue by krpeacock** [dfinity/sdk#2002]
Steps to reproduce:

* Deploy canister with default identity
* Switch to different identity
* run `dfx deploy --network ic` 

Outcome:
* it gets stuck in step Starting batch. with no errors.

Expected outcome: 
* It should report an error

reported in https://forum.dfinity.org/t/dfx-0-9-0-gets-stuck-when-trying-to-deploy-canister-with-wrong-identity/10623

**Comment by sesi200** [comment]
Does not happen with dfx 0.10.0 anymore.
