### ISSUE TITLE
Bug: canister upgrade rejected if module hash is unchanged.

### ISSUE THREAD

**Issue by crusso** [dfinity/sdk#2015]
Calling dfx canister install --mode upgrade will fail to do the upgrade if the module hash has not changed, and there seems to be no way to force the upgrade without re-compiling the canister with change that affects the hash.

I can see this might be an optimization in some scenarios but its actually a legitimate use-case to want to upgrade a canister even if its hash has not changed, e.g. to test upgrades or to reset wasm memory to initial conditions after a leak.

Can we change this behaviour, or at least allow a --force option to override the current behaviour?

**Comment by chenyan-dfinity** [comment]
Another use case is to deploy the Wasm with a different init args, which is not possible at the moment.
