### ISSUE TITLE
URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by leo-blockchain** [dfinity/sdk#2088]
cargo build

  cargo:rerun-if-env-changed=DFX_ASSETS
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/nix/sources.json
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/scripts/dfx-asset-sources.sh
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/scripts/prepare-dfx-assets.sh
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/assetstorage.did
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/assetstorage.wasm
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/ui.did
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/ui.wasm
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/wallet.did
  cargo:rerun-if-changed=/Users/name/Documents/dfinity/sdk/src/distributed/wallet.wasm
  cargo:error=unable to run /Users/name/Documents/dfinity/sdk/scripts/prepare-dfx-assets.sh:
  cargo:error=curl: (3) URL using bad/illegal format or missing URL

**Comment by sesi200** [comment]
As we had no other reports of this I assume this is fixed. Please reopen if this is not the case.
