### ISSUE TITLE
RFC: Per network configuration

### ISSUE THREAD

**Issue by bitdivine** [dfinity/sdk#2119]
# Motivation

We have a canister that has several deployed instances.  Each deployed instance is represented by an entry in `dfx.json` under `networks.$DEPLOYMENT_NAME`.  We have different configuration that is used when building the wasm for each deployment.  It would be good to have a clean way of passing that configuration.

### Example of usage
The deployments depend on external canisters that are not deployed by the current project.  The location of the external canisters vary by network.  Thus it would seem natural to store the per-network configuration like this:

```
dfx.json
{ "networks": {
    "network1": {
      "config": {  <----- NEW per-network config.
         "SOME_EXTERNAL_SERVICE": "https://ahsdgfhjdsgfkjsagf.ic0.app"  <-- Sample entry
      },
      "providers": [
        "https://ic0.app/"
      ],
      "type": "persistent"
    },
    "network1": {
      "config": {  <----- NEW per-network config.
         "SOME_EXTERNAL_SERVICE": "https://differentdifferentdifferent.ic0.app"  <-- May differ by network entry
      },
      "providers": [
        "https://ic0.app/"
      ],
      "type": "persistent"
    }
  }
}
```

# Design options
### `NETWORK` environment variable.
- Theoretically `NETWORK` could be provided as an environment variable when dfx runs `build.sh`.  Then build.sh could look up the custom config from dfx.json by itself.
  - Con: I would prefer the build to be ignorant of which network it is built for; the build should be a pure function with the custom config as an input and wasm as an output.
  - Pro: Simple to implement.
  - Pro: Flexible.  This handles some cases I had not thought about before.
### Pass the custom config to `build.sh`
`dfx` could copy the custom config for the current network into a temp file and then pass the location of the temp file to build.sh as an environment variable.
### Pass only environment variables
In this scenario custom config could only be of the form `Map<String,String>` and the config entries would be set as environment variables to build.sh
- Pro: Saves `build.sh` from having to parse a JSON config.  Maybe this would be more convenient in some cases.
- Con: Restricts what can be provided as custom config.

# Next Steps
- [ ] Basic concept review:
  - [ ] Developer feedback
  - [ ] Feedback from the SDK team
- [ ] Design
- [ ] Implement
- [ ] Document

**Comment by adamspofford-dfinity** [comment]
> Theoretically NETWORK could be provided as an environment variable when dfx runs build.sh. Then build.sh could look up the custom config from dfx.json by itself.

This is already done, the variable is called DFX_NETWORK. Given that that's the bare minimum to be able to implement this per-project in your build script, would what essentially amounts to a string map still be worthwhile over what the build systems already offer?
