### ISSUE TITLE
Release drafter for automatic release descriptions

### ISSUE THREAD

**Issue by domwoe** [dfinity/sdk#2142]
I noticed that we don't always have release notes.
We used the following Github Action (https://github.com/marketplace/actions/release-drafter) in some projects in the past which can automatically create release notes based on PR/commit messages. This could be a low effort  approach to some nice looking release notes :)

**Comment by sesi200** [comment]
We use the auto-generate feature for release notes by now, as you can see here: https://github.com/dfinity/sdk/releases
