### ISSUE TITLE
Error: The replica returned an HTTP Error: Http Error: status 500 Internal Server Error, content type "" , content: Internal Server Error

### ISSUE THREAD

**Issue by Tudor44** [dfinity/sdk#2157]
Hello,

I have this error with the last version of dfx (0.9.3). It occurs when I try to build the hello basic dapp.

This is the output console of Replica:

``Apr 25 21:18:22.528 WARN s:i5ycw-o7hiz-ka5aw-laszm-nvmm3-rykjp-7e2cb-wfybp-usj3r-ozdgu-sae/n:n2qda-3igrh-isuq7-2m4qn-jbccx-qmvrg-dbdur-zr65q-hzi5z-gbbsb-aqe/ic_p2p/advert_utils AdvertRequestBuilder::new(): advert_config = Some(GossipAdvertConfig { best_effort_percentage: 20 })
thread 'tokio-runtime-worker' panicked at 'Could not open temporary port report file: No such file or directory (os error 2) at path "/home/gdorsi/hello/.dfx/replica-configuration/.tmpERsxWC"', http_handler/src/lib.rs:220:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'replica-actor' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot start the replica: Timeout', src/dfx/src/actors/replica.rs:279:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 Apr 25 23:24:38.806 WARN Internal Error during request:
hyper::Error(
    Connect,
    ConnectError(
        "tcp connect error",
        Os {
            code: 111,
            kind: ConnectionRefused,
            message: "Connection refused",
        },
    ),
)``

**Comment by sesi200** [comment]
Can you try to install dfx 0.10.0 (`DFX_VERSION="0.10.0" sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"`) and try again?

**Comment by Tudor44** [comment]
Thanks for your suggestion.

But I have another similar error when deploying a simple hello canister example: 

`dfx.json not found, using default.
Error: Failed during wallet creation.
Caused by:
  Encountered an error while trying to fetch the root key.
    The replica returned an HTTP Error: Http Error: status 500 Internal Server Error, content type "", content: Internal Server Error`
    
While in the replica side I have this other:
` May 06 23:36:41.595 WARN Internal Error during request:
hyper::Error(
    Connect,
    ConnectError(
        "tcp connect error",
        Os {
            code: 111,
            kind: ConnectionRefused,
            message: "Connection refused",
        },
    ),
)`

**Comment by sesi200** [comment]
Can you try re-starting the replica with the `--clean` flag? That would then be `dfx start --clean`. We've had someone hit a similar error because they restarted their computer while the replica was running, resulting in a broken state written to disk.

**Comment by Tudor44** [comment]
I have retried but I have the same problem. This is the situation after the `dfx deploy` command...

![Immagine 2022-05-10 225610](https://user-images.githubusercontent.com/6132033/167720551-4acec62a-4249-4a4c-9f62-60927e6cbd75.png)

**Comment by adambratschikaye** [comment]
Are you running this under WSL? If so, which version of WSL is it? And in general which OS/version are you running?

**Comment by sesi200** [comment]
Thanks for the details, we were hoping it was an issue with WSL 1 instead of WSL 2. For the moment it's broken and there's nothing you can do, but the runtime team is working on a fix. Looks like `memfd_create` is not supported and they need to create a workaround for WSL.

**Comment by Tudor44** [comment]
Thank you for the support.
If there is something that I can test to help the community, I m available. 
Meanwhile, is better to use a Linux OS to install the Replica?

**Comment by sesi200** [comment]
Hi @Tudor44

If you're still willing to test: with #2272 merged, the fix should be included in dfx. If you could try to run dfx start with the latest master (instructions [here](https://github.com/dfinity/sdk/blob/master/.github/CONTRIBUTING.adoc#developing-dfx)) and report if if works that would be great!

**Comment by sesi200** [comment]
So it looks like the original error is fixed (no more panic), but there's still issues. From the outside it looks like the same error: Just failing to respond to the first request. Without any extra info I'm not sure we can do much at the moment.

I'll forward this to the correct team, but I can't make any promises beyond that.

**Comment by Tudor44** [comment]
Thank you @sesi200.
 If there are some things for help the improvments. Check logs or something else I m available as always,
 
 Warm Regards,
 Gaetano.
