### ISSUE TITLE
Error when trying to forward to project dfx:

### ISSUE THREAD

**Issue by Techi-Dev** [dfinity/sdk#2189]
Error accruing when starting dfx  on the server

I have tried to solve it using some recommended solution with the  code stated below and it didn't solve the issue

`DFX_VERSION=0.8.3 sh -ci "$(curl -sSL https://sdk.dfinity.org/install.sh)"
`

 What do I need to do to avoid this error? if you have encountered the same issue and solved it ,  You can state the solution you have used .

```
Warning: The version of DFX used (0.8.4) is different than the version being run (0.9.3).
This might happen because your dfx.json specifies an older version, or DFX_VERSION is set in your environment.
We are forwarding the command line to the old version. To disable this warning, set the DFX_WARNING=-version_check environment variable.

Error when trying to forward to project dfx:
Unknown version '0.8.4'.
Installed executable: 0.9.3
```

**Comment by sesi200** [comment]
In `dfx.json`, there's a field that should look like `"dfx": "0.8.4"` that instructs dfx to run on version 0.8.4. But AFAIK there never was a version 0.8.4. If you simply delete that line in `dfx.json`, the latest installed version should run.
