### ISSUE TITLE
The build step failed for canister

### ISSUE THREAD

**Issue by Techi-Dev** [dfinity/sdk#2193]
dfx Error, trying to debug it.

 !
  <exp_nullary(ob)>
  <binop> <exp(ob)>
  ; seplist(<dec>,<semicolon>)
  or <exp_bin(ob)>
  <unassign> <exp(ob)>
  <relop> <exp_bin(ob)>
  . <id>
  : <typ_nobin>
  <binop> <exp_bin(ob)>
  <binassign> <exp(ob)>
  and <exp_bin(ob)>
  <unop> <exp_bin(ob)>
  <inst> <exp_nullary(ob)>
  [ <exp(ob)> ]

**Comment by sesi200** [comment]
Insufficient information. Feel free to re-open this issue if you have relevant information to reproduce the issue.
