### ISSUE TITLE
dfx deploy --argument only works with raw as an argument-type

### ISSUE THREAD

**Issue by GLicDEV** [dfinity/sdk#2205]
When trying to receive arguments from the init() function, I noticed that sending idl arguments with "dfx deploy" doesn't work, while sending raw didc encoded arguments worked as expected.

This is the rust code running on the canister:

```
#[init]
fn init(foo: String) {
    ic_cdk::print(format!("Init: {:?}", foo));
}
```

When running the following commands, it always results in an error:
```
dfx start --clean
dfx canister create ic_test
dfx canister install --argument '("Test")' ic_test

[OR]

dfx deploy ic_test --argument '("Test")'
```

Results in 

```
Error: The Replica returned an error: code 5, message: "Canister rrkah-fqaaa-aaaaa-aaaaq-cai trapped explicitly: Custom(No more values on the wire, the expected type text is not opt, reserved or null)"
```

When using a didc encoded parameter, I get the desired response:
```
$ didc encode '("Test")'
4449444c0001710454657374

$ dfx deploy ic_test --argument 4449444c0001710454657374 --argument-type raw

[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Init: "Test"
```

I have ran all these tests with the following versions:
```
$ dfx --version
dfx 0.9.3

$ didc --version
didc 0.1.4
```

For context, see this forum post: https://forum.dfinity.org/t/how-to-pass-install-arguments-from-dfx/12977

**Comment by chenyan-dfinity** [comment]
I think you forget to update the did file to include the init args, e.g.
```
service : (text) -> {
  your_canister_method: ...
}
```

**Comment by GLicDEV** [comment]
@chenyan-dfinity, you are of course correct! Adding (text) -> for my service in the .did file solved the problem, and now the two options (IDL and RAW) both work! Thank you.

I haven't even thought about the did file, since I use the following pattern to export the did interface:

```
// Auto export the candid interface
candid::export_service!();

#[query(name = "__get_candid_interface_tmp_hack")]
#[candid_method(query, rename = "__get_candid_interface_tmp_hack")]
fn __export_did_tmp_() -> String {
    __export_service()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_candid() {
        let expected = String::from_utf8(std::fs::read("ic_test.did").unwrap()).unwrap();

        let actual = __export_service();

        if actual != expected {
            println!("{}", actual);
        }

        assert_eq!(
            actual, expected,
            "Generated candid definition does not match expected did file"
        );
    }
}

```

Is the __export_did_tmp_() supposed to pickup and output the proper service definition? For the moment it just outputs "service: {}" ... I even tried decorating the init() fn like so:

```
#[candid_method(update)]
#[init]
fn init(foo: String) {
    ic_cdk::print(format!("Init: {:?}", foo));
```

The __export_did_tmp() picks up the init fn, adds it to the service, but the service signature still doesn't include the parameters. Perhaps this is something not considered at the time?

**Comment by chenyan-dfinity** [comment]
You can use `#[candid_method(init)]` for the init function.

We have plans to add `candid_method` into the CDK, so that users don't need to do this manually.

**Comment by GLicDEV** [comment]
Thank you! I can confirm that ```#[candid_method(init)]``` works as expected!
