### ISSUE TITLE
Environment-specific canisters?

### ISSUE THREAD

**Issue by paulyoung** [dfinity/sdk#2216]
Is there a way to declare in `dfx.json` that a canister should only be deployed to certain environments?

For example, to configure ledger or internet identity canisters for local deployment only.

cc @sesi200 in case this relates to the work mentioned in https://github.com/dfinity/sdk/issues/2199#issuecomment-1125992831

**Comment by sesi200** [comment]
I think you're looking for the remote canister feature: #2010. Does this solve your problem?

**Comment by paulyoung** [comment]
Possibly! I'll give it a try and report back. Thanks.

**Comment by paulyoung** [comment]
This appears to do what I want, at least locally. I did the following.

I'm not sure yet if it's necessary to specify the `candid` field again under `remote`, or if the canister ID is the right one.

```json
{
  "canisters": {
    "internet_identity": {
      "type": "custom",
      "wasm": "result/remote/internet_identity/internet_identity_dev.wasm",
      "candid": "result/remote/internet_identity/internet_identity.did",
      "remote": {
        "candid": "result/remote/internet_identity/internet_identity.did",
        "id": {
          "ic": "rdmx6-jaaaa-aaaaa-aaadq-cai"
        }
      }
    }
  }
}
```

I'm not sure https://github.com/dfinity/sdk/issues/2085 is what I'd want but perhaps some version of `"type": "remote"` would improve things.

**Comment by paulyoung** [comment]
How important is it to use the correct `id` for a remote canister. I need to set up some local third-party canisters for development but I don't know their canister IDs. Even for Internet Identity I had to go digging.

I think what I might want is a "only install these locally" option (or something equivalent) without having to provide the extra info.

**Comment by paulyoung** [comment]
As I mentioned in https://github.com/internet-identity-labs/NFID-SDK/discussions/141#discussioncomment-3370064, I'll try to use `dfx canister install --wasm <path> <canister name>` instead.

**Comment by paulyoung** [comment]
Apparently that still requires the same entries in `dfx.json` as before so it doesn't help at all.

**Comment by sesi200** [comment]
> How important is it to use the correct id for a remote canister?

Any calls you perform to this canister go to the entered ID. If you enter the wrong ID, the wrong canister IDs will be baked into your wasm if you reference these canisters.

> I think what I might want is a "only install these locally" option (or something equivalent) without having to provide the extra info.

Internally, we're discussing about the idea of something like docker-hub for canisters that would make this even more convenient. Unrelated question (i.e. don't take this question as "we're working to wards this"): Would it be a solution for you if the individual projects (say II or the ledger canister) had a ready-to-copy-paste snippet that would contain the relevant remote configuration?

**Comment by paulyoung** [comment]
> Any calls you perform to this canister go to the entered ID. If you enter the wrong ID, the wrong canister IDs will be baked into your wasm if you reference these canisters.

The thing is, I’m (currently) not referencing those canisters. Both II and NFID provide URLs with domain names for interacting with them.

This might change with some other canisters I plan to add, like canistergeek.

> Would it be a solution for you if the individual projects (say II or the ledger canister) had a ready-to-copy-paste snippet that would contain the relevant remote configuration?

It would help if projects like NFID and canister geek provided this info. My main concern is knowing the canister ID.

I also have more general concerns with local vs remote canisters behaving differently, but that’s a different topic.
