### ISSUE TITLE
IDL generation for an actor results in an automatic error if using NodeJS

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/sdk#2240]
## The Issue

Currently, if one is building NodeJS tooling to interact with an actor (i.e. upgrade scripts, integration tests, etc.) and wants to use dfx generate as part of their build pipeline, they run into an error with the exported "ready-to-use" actor given by

[Source](https://github.com/dfinity/sdk/blob/0a7833890cc44d0515f317dbb84c6931cf78fb09/src/dfx/assets/language_bindings/canister.js#L38.)

```
/**
 * A ready-to-use agent for the {canister_name} canister
 * @type {import("@dfinity/agent").ActorSubclass<import("./{canister_name}.did.js")._SERVICE>}
 */
 export const {canister_name} = createActor(canisterId);
```

This produces the following error
```
AgentError: Fetch implementation was not available. You appear to be in a Node.js context, but global.fetch was not available.
```
This happens because global.fetch is not available in the Node context, and the auto-generated code is executing the `createActor()` method, not giving the developer a chance to implement their own workaround without editing the generated `index.js` file itself.

## My current workaround

Step 1) For a library I'm writing that is both NodeJS and browser compatible, I've written the following function which binds the fetch that is used based on the user's environment.

```
import fetch from "node-fetch";

/**
 * Gets the appropriate fetch for the given environment (i.e. browser, node)
 *
 * @ignore
 * @returns fetch
 */
function getDefaultFetch() {
  if (typeof window !== "undefined") {
    // Browser context
    if (window.fetch) {
      return window.fetch;
    }
    throw new Error(
      "Fetch implementation was not available. You appear to be in a browser context, but window.fetch was not present."
    );
  } else if (typeof global !== "undefined") {
    return fetch as unknown as typeof globalThis.fetch;
  }

  // @ts-ignore
  const self: Window & typeof globalThis = this;
  if (typeof self !== "undefined") {
    if (self.fetch) {
      return self.fetch;
    }
  }

  throw new Error(
    "Fetch implementation was not available. Please provide fetch to the HttpAgent constructor, or ensure it is available in the window or global context."
  );
}
```

Step 2)  At this point if I were to run the code, I would still see fetch error because the `getDefaultFetch()` function that I wrote is not used in the auto-generated `createActor()` function. I now have to go into the declaration file and comment out the result of the 
```
export const {canister_name} = createActor(canisterId);
```
code even though I am not using this code in my library (I've built my own generic `createActor()` function, and I just want the IDL and type bindings).

## What a solution might look like

I've talked to several others in the community that are building developer tooling, such as @di-wu (https://github.com/aviate-labs), and the current workaround is for us to write a script that auto-comments out the last line of all index.js files that get generated. 

This is a bit of a hack however, and will undoubtedly affect new developers that try to build NodeJS tooling, resulting in shared wasted time. 

I see two possible solutions: 

1. Instead of exporting a value which means calling createActor directly and exporting it like
```
export const {canister_name} = createActor(canisterId);
```

instead export a function
```
export const generate_{canister_name} => () { return createActor(canisterId) };
```

2. Use the `getDefaultFetch()` implementation I've provided in the My Current Workaround section above ☝️  in the auto-generated code.

With either of these solutions, if I'm then trying to import the IDL from the generated `index.js` file, as a developer building NodeJS tooling I'm not "forced" into dealing with this error through hacky solutions.

**Comment by ByronBecker** [comment]
Just checking in regarding this issue 👋 

Would it be possible to add a `--node` flag or something of the sort to `dfx generate` that would remove this line https://github.com/dfinity/sdk/blob/master/src/dfx/assets/language_bindings/canister.js#L42 from the auto-generated declaration files?

Maybe this is something like `environment: Option<String>` in the [`GenerateOpts`](https://github.com/dfinity/sdk/blob/d9cd318be2a0be7204a5df1f9f7418f7f603ca06/src/dfx/src/commands/generate.rs#L15), 

and then it getting passed down to https://github.com/dfinity/sdk/blob/d9cd318be2a0be7204a5df1f9f7418f7f603ca06/src/dfx/src/commands/generate.rs#L85

and then making it's way into https://github.com/dfinity/sdk/blob/d9cd318be2a0be7204a5df1f9f7418f7f603ca06/src/dfx/src/lib/models/canister.rs#L679?

**Comment by krpeacock** [comment]
This was resolved by this commit -https://github.com/dfinity/sdk/commit/32c168ec75ca4ca8dd409db59e4b2d78444bbfb5

To use the feature in your code, add the setting of 

`canister -> declarations -> "node_compatibility": true`
