### ISSUE TITLE
How to create an account by sdk or nns-js

### ISSUE THREAD

**Issue by hankeke** [dfinity/sdk#2254]
I want to create an ICP account through the API. Is there a way to do this? I want to write an app to create an account and transfer  ICP tokens. At present, I haven’t found the corresponding API. Can I ask if this can be realized?

**Comment by sesi200** [comment]
You can generate new identities using the `dfx identity new` command: https://internetcomputer.org/docs/current/references/cli-reference/dfx-identity#dfx-identity-new

In the future, please use forum.dfinity.org for similar inquiries.
