### ISSUE TITLE
imported pem identity cause:  A key was rejected by Ring: InvalidEncoding: InvalidEncoding

### ISSUE THREAD

**Issue by skyh24** [dfinity/sdk#2260]
version: 
quill 0.2.15
dfx 0.10.1

operation:
`quill generate --seed-file whitelist.txt --pem-file whitelist.pem`
and 
`dfx identity import --disable-encryption whitelist ./credentials/whitelist.pem`
and use whitelist identity

error occur：
```
> dfx canister call 
Error: Failed to create AgentEnvironment.
Caused by: Failed to create AgentEnvironment.
  Failed to create AgentEnvironment for network 'local'.
    Failed to instantiate selected identity.
      Failed to instantiate identity with name 'whitelist'.
        Failed to load identity 'whitelist'.
          Cannot read identity file 'whitelist': A key was rejected by Ring: InvalidEncoding: InvalidEncoding
```

**Comment by skyh24** [comment]
dfx 0.9.3 has no this error. Use in m1mac

**Comment by lwshang** [comment]
Hi @skyh24, the issue was in `quill`.
We have fixed it and released a new version of `quill`. https://github.com/dfinity/quill/releases/tag/v0.2.17
Could you try this new version and see if it works for you?
