### ISSUE TITLE
DFX clogs up logging with cycles invariant warning

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/sdk#2278]
DFX Version: 0.10.1
Machine: 2019 Macbook Pro 16"

While running DFX locally the logging is spamming this warming message:
```
Jun 19 02:02:47.545 WARN s:vdfz6-tmyxv-r2izp-bojxn-zdwcj-hj6fb-4s727-3ztw7-t2kdt-4cko4-uqe/n:kfiph-ootot-okocg-
45m5g-qfkab-wuddc-kj6fq-wzlw7-eioly-xusen-vqe/ic_execution_environment/scheduler At Round 11399 @ time 
2022-06-19 02:02:46.864027 UTC, the resulted state after execution does not hold the in-out cycles invariant: cycles at
 beginning of round 295369640373082 were fewer than cycles at end of round 299269640373082, messaging: 
{"round":11399,"canister_id":null,"message_id":null}
```

Pretty much any time I interact with a replica it spits the above message out a few times (with different cycles counts).

Is there a way that I can temporarily disable this cycles-based logging?

**Comment by sesi200** [comment]
This has been fixed here: https://github.com/dfinity/ic/commit/efd2c9f5bf19ee640284d8f4b31982d53b9c17f2. The next release of dfx will include the fix.
