### ISSUE TITLE
docs: dfx new --type rust print out links to motoko

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/sdk#2296]
At the end of the `dfx new myproject --type rust` process, dfx print the same information in the console as those for Motoko.
It would be handy to print out the links for the Rust dedicated documentation.

> To learn more before you start coding, see the documentation available online:
>
> - Quick Start: https://sdk.dfinity.org/docs/quickstart/quickstart-intro.html
> - SDK Developer Tools: https://sdk.dfinity.org/docs/developers-guide/sdk-guide.html
> - Motoko Language Guide: https://sdk.dfinity.org/docs/language-guide/motoko.html
> - Motoko Quick Reference: https://sdk.dfinity.org/docs/language-guide/language-manual.html

**Comment by sesi200** [comment]
Internal ticket: [SDK-570](https://dfinity.atlassian.net/browse/SDK-570)

**Comment by peterpeterparker** [comment]
Thx 👍
