### ISSUE TITLE
Join an existing local dfx server

### ISSUE THREAD

**Issue by bitdivine** [dfinity/sdk#2388]
# Motivation
We wish to run several projects on the same local dfx server.

We are aware that the network configuration may be refactored.  It may be that this is just a polyfill until some bright new future.

# Proposal
```
dfx start --join
```
looks for an existing locally running dfx server and "joins" that by pointing the local `.dfx` directory as a link at the .dfx of the running server.

# Polyfill
You can get this functionality now with: https://gist.github.com/bitdivine/e997e8333d374c0b5add5aaeb85acb66

**Comment by smallstepman** [comment]
Happy to tell you that the feature called "system-wide dfx" is underway - it will help you run several projects on the same local dfx server out-of-the-box

**Comment by bitdivine** [comment]
@smallstepman  Super!  Happy to tell you that the polyfill works well in the meantime! :-)

**Comment by ericswanson-dfinity** [comment]
Closing this as the "system-wide dfx" changes are [merged](https://github.com/dfinity/sdk/pull/2430) and will be included in dfx 0.12.0.  Thanks for pointing to an alternative in the meantime!
