### ISSUE TITLE
Run upgrade if wasm unchanged but arguments changed

### ISSUE THREAD

**Issue by nmattia** [dfinity/sdk#2400]
By default (without `--upgrade-unchanged`) `dfx` won't upgrade a canister, even if its `--argument` has changed:

``` bash
$ dfx canister install --mode upgrade --argument '<new arg>' my_canister

Module hash c0323214bb28a05be8b0e01e07c8000809a680d982bb0718983317ddda4770e8 is already installed.
```

I'm not sure if this is even feasible to figure out if the args changed, but if so, it would make sense to upgrade the canister.

**Comment by sesi200** [comment]
I understand the use case, but I do not see how this can be detected. If you baked in the used arguments in a custom section of the WASM, then it would work, but this is not something dfx should do on its own. As part of a custom build/deploy script this could be a solution for you.

**Comment by nmattia** [comment]
That's what I thought, though I wondered if the canister could give you e.g. a hash of the arguments or something.

Thanks!
