### ISSUE TITLE
dfx should not require a build npm script when deploying asset canisters

### ISSUE THREAD

**Issue by lastmjs** [dfinity/sdk#2418]
The dfx deploy process for asset canisters throws an error if there is a root level package.json without a build npm script. It shouldn't matter if there is a script or not, if the script does not exist that should be valid.

**Comment by sesi200** [comment]
Link to internal ticket: https://dfinity.atlassian.net/browse/SDK-657

**Comment by dfx-json** [comment]
The asset canister now supports a custom build script. The default behavior of dfx will continue to be to attempt to call npm run build

**Comment by lastmjs** [comment]
Hi, I'm not sure why this issue was closed, as according to the last comment the issue was not resolved (though I haven't checked on the behavior in a long time). The problem is that developers should not be forced to have a build script. `dfx` should detect if a build script is present, and execute it if it is. But it should not fail if there is no build script defined by the developer, as having no build script is valid.
