### ISSUE TITLE
dfx start fails if dfx.json is malformed

### ISSUE THREAD

**Issue by nmattia** [dfinity/sdk#2423]
When starting `dfx` with a bad `dfx.json`, the command will fail, although I don't understand why `dfx` is even reading the `dfx.json`:

```
$ cat dfx.json
{ "canisters": "yes" }
$ dfx start
Error: Failed to read config from current working directory.
Caused by: Failed to read config from current working directory.
  Failed to read config from directory /Users/nicolas/internet-identity/demos/using-dev-build.
    Failed to load config from /Users/nicolas/internet-identity/demos/using-dev-build/dfx.json.
      invalid type: string "yes", expected a map at line 1 column 20
```

I can definitely work around this, although I still find the behavior surprising. No error is thrown if there is no `dfx.json`.

**Comment by sesi200** [comment]
`dfx.json` can enable replica features, such as `canister_http` or the BTC adapter. If the file is malformed, `dfx start` may run with the wrong configuration.

**Comment by nmattia** [comment]
Does that mean that I should have exactly one running replica per dfx.json? how should I deal with multiple canister projects?

**Comment by sesi200** [comment]
@ericswanson-dfinity is working on the system-wide dfx feature, which has progressed quite far already. Before this is ready, it's simply painful. You probably should have one main place where you start the replica from, and go from there. Some people had some success with symlinking different dfx.jsons together.
