### ISSUE TITLE
`dfx schema` requires a valid `dfx.json`

### ISSUE THREAD

**Issue by paulyoung** [dfinity/sdk#2437]
I was setting up a new remote canister and was trying to see if I could omit some fields.

I wanted to view the schema to get a better sense of what I was doing but I couldn’t because I had omitted some required fields. The file was still valid JSON.

It seems like an unnecessary coupling to not be able to view the schema because of the state of the file.

**Comment by sesi200** [comment]
Indeed, that's a silly restriction. My bad, I didn't think I should test for that when I wrote `dfx schema`. Made a [ticket](https://dfinity.atlassian.net/browse/SDK-667) for myself, but it's not at the top of my priorities for now.
