### ISSUE TITLE
dfx canister install --mode upgrade continues upgrade on failed build (rust)

### ISSUE THREAD

**Issue by MrWoo034** [dfinity/sdk#2442]
## Description
When running a script to upgrade a canister with code changes for local testing, when there is an error in the code that produces a compilation error the upgrade continues.  

e.g. 
`dfx canister install society_rs --wasm ./target/wasm32-unknown-unknown/release/society-rs-opt.wasm.gz --mode upgrade`
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/16422281/184449710-73b45d99-592b-4828-b8c3-a2652c9a457e.png">

## Expected Behavior
If the build fails the upgrade should not proceed.

## System
```
dfx -V
dfx 0.10.1
```

**Comment by sesi200** [comment]
Cannot reproduce on the latest version (0.11.1) and also not on your version (0.10.1). I started with `dfx new --type rust --no-frontend`.
Can you help me with steps to reproduce, starting with `dfx stop`, `rm -rf .dfx`, and `dfx start --clean`, please?

**Comment by sesi200** [comment]
Haven't had any activity on this for almost 2 months. Assuming this is fixed. Please reopen if this is not the case.
