### ISSUE TITLE
`dfx` attempts to add candid service metadata to Gzip compressed Wasm, and fails

### ISSUE THREAD

**Issue by paulyoung** [dfinity/sdk#2459]
I compressed my canister Wasm using `gzip --to-stdout --best myproject.wasm > myproject.wasm.gz` and encountered this error:

`Failed to add candid service metadata from .dfx/local/canisters/myproject/myproject.did to .dfx/local/canisters/myproject/myproject.wasm.: Failed to parse file .dfx/local/canisters/myproject/myproject.wasm: Bad magic number (at offset 0)`

The `"wasm"` field of my canister in `dfx.json` points to `myproject.wasm.gz` but if I change it back to `myproject.wasm` I don't get the above error.

I'm building my Rust canister using a custom `build` step. Maybe that has something to do with it: https://github.com/dfinity/sdk/blob/97b3de9285c1dcf0e565453b80379c957fe403e4/CHANGELOG.md#fix-dfx-now-only-adds-candidservice-metadata-to-custom-canisters-that-have-at-least-one-build-step

I'm using dfx 0.11.1

**Comment by paulyoung** [comment]
To clarify, the `"type"` field for my canister is set to `"custom"`

**Comment by sesi200** [comment]
Thank you for the bug report. We have ongoing work related to gzipped wasm files, hopefully I can combine the tasks. Internal ticket: [SDK-696](https://dfinity.atlassian.net/browse/SDK-696)

**Comment by paulyoung** [comment]
Thanks. Perhaps I can work around it by tweaking my `build` command.

https://github.com/dfinity/sdk/blob/5e72d2126d2bf6d3c93c9f9bcc146d19053ffe24/src/dfx/src/lib/builders/custom.rs#L115-L123

**Comment by paulyoung** [comment]
Based on the discussion at the link below I think this may only be an issue with `dfx deploy`, and be the same problem that was reported in https://github.com/dfinity/sdk/issues/2357.

https://forum.dfinity.org/t/dfx-0-11-0-is-promoted-with-breaking-changes/14327/3?u=paulyoung

Apparently `dfx canister install myproject --wasm myproject.wasm.gz` would work.
