### ISSUE TITLE
Failed to parse config from file 'dfx/state/replicated_state/ic.json5': missing field `listening_port`

### ISSUE THREAD

**Issue by lau-bin** [dfinity/sdk#2535]
The commands "dfx start", "dfx start --clean" and "dfx replica" throw an exception: Failed to parse config from file 'dfx/state/replicated_state/ic.json5': missing field `listening_port` with the "dfx-0.12.0-beta.1-x86_64-linux" version.      
This puts the process in a state where it rejects attempts to install canisters with ic-nns-init, I haven't tried other ways of calling the process but it looks like it's broken.    
I added the missing property to the generated config while preventing it's deletion (dfx always deletes the config on start) without success.

**Comment by sesi200** [comment]
We have tests that cover the various ways to start the replica on Linux. Are there any extra logs you can share?

**Comment by sesi200** [comment]
I haven't seen any reports of this for both 0.12.0-beta.2 and 0.12.0-beta.3 so I'll close this for now. If the issue reappears, feel free to re-open.
