### ISSUE TITLE
Breaking changes to language binding assets associated with dfx generate in 0.12.0-beta.3 result in idlFactory type error.

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/sdk#2615]
I currently have some software tooling that generates canister declaration files and then copies them over to another directory.

One of the developers using this tooling on the `0.12.0-beta.3` version just reported the following error when trying to start up their frontend after copying over the declarations from the backend canister directory. (I have a script that runs dfx generate before copying over the declarations from the backend to the frontend directory).

It results in the following error.

```
TS2305: Module '"../declarations/index/index"' has no exported member 'idlFactory'.
```

For comparison, no other developers (running <= 0.11.x) have this same issue. 

I dug a bit deeper into this and found that it's because in `0.12.x` the declarations generate an additional index.d.ts file that is not present in dfx versions `<= 0.11.x does not`. (See https://github.com/dfinity/sdk/blob/master/src/dfx/assets/language_bindings/index.d.ts.hbs)

Because of this addition, now TypeScript expects for the idlFactory type to be defined in this `index.d.ts` file and will complain if it is not present there (with the error shown above), instead of just pulling it from `./<canister_name>.did.js.

**Comment by sesi200** [comment]
@nathanosdev is looking into this. Thank you for reporting!
