### ISSUE TITLE
Broken link to motoko lang guide in readme template

### ISSUE THREAD

**Issue by devidw** [dfinity/sdk#2708]
In the scaffolded README.md of a new project, the _Motoko Programming Language Guide_ link points to a 404.

https://github.com/dfinity/sdk/blob/master/src/dfx/assets/new_project_motoko_files/README.md

It redirects from:

```
https://sdk.dfinity.org/docs/language-guide/motoko.html
```

To:

```
https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/index
```

Which does not exist.

I guess it should be:

```
https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/motoko/
```

### Meta

`dfx --version`:
```
dfx 0.11.2
```

<details><summary>Further log output</summary>
<p>

```
<log output>
```

</p>
</details>

**Comment by sesi200** [comment]
Thank you for the report and very nicely prepared steps to fix!
