### ISSUE TITLE
svelte-check issue - module has no exported member 'idlFactory'

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/sdk#2763]
In a SvelteKit project, when declarations are checked with `npm run check`, an error will be thrown:

> /.../src/declarations/backend/index.js:4:10
> Error: Module '"./backend.did.js"' has no exported member 'idlFactory'. 
> // Imports and re-exports candid interface
> import { idlFactory } from './backend.did.js';
> export { idlFactory } from './backend.did.js';

> /.../src/declarations/backend/index.js:5:10
> Error: Module '"./backend.did.js"' has no exported member 'idlFactory'. 
> import { idlFactory } from './backend.did.js';
> export { idlFactory } from './backend.did.js';

Reproduction: pull request in the examples in review https://github.com/dfinity/examples/pull/385

**Comment by sesi200** [comment]
@nathanosdev any chance this is related to something you did a while back? You might already know what the problem is

**Comment by nathanosdev** [comment]
The example is using dfx v0.11.2, so it doesn't include that change that I made. But this is the reason why I made that change.

Without the typescript declarations you can't do `import { createActor } from '../../../declarations/backend';` in Typescript and need to do `const { createActor } from '../../../declarations/backend';` instead. 

If I make that change on @peterpeterparker's branch then `npm check` passes fine.

But it would be better to upgrade the example to use dfx v12 to make use of the fix I made for this. I think we can close this as "already fixed" :)

**Comment by peterpeterparker** [comment]
Indeed the type declaration generated with dfx v0.12.0 solves this. Thanks @nathanosdev 

p.s.: I bumped dfx in the SvelteKit branch example
