### ISSUE TITLE
Absolute path for type declarations

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/sdk#2768]
I tried the following:

1. init default rust project
2. deploy

I expected to see this happen: 
For the `Generating Type declarations`, I excepted relative paths for all declarations

Instead, this happened: 
`did` file has absolute Path
<img width="864" alt="Screenshot 2022-11-16 at 14 00 50" src="https://user-images.githubusercontent.com/32162112/202187686-61d663d3-c851-42e2-aaf9-d91ea30e805a.png">

### Meta

`dfx --version`:
```
0.12.0
```

<details><summary>Further log output</summary>
<p>

```
<log output>
```

</p>
</details>

**Comment by sesi200** [comment]
Thanks for the report! Tracked in [SDK-859](https://dfinity.atlassian.net/browse/SDK-859)
