### ISSUE TITLE
`--no-frontend` flag

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/sdk#2771]
I tried the following:

1. `dfx new --no-frontend`

I expected to see this happen: No asset canister present, no entries in `dfx.json`

Instead, this happened: Asset canister and entrie present.

### Meta

`dfx --version`:
```
0.12.0
```

<details><summary>Further log output</summary>
<p>

```
<log output>
```

</p>
</details>

**Comment by letmejustputthishere** [comment]
if this behaviour is changed, we need to update this [tutorial](https://internetcomputer.org/docs/current/developer-docs/build/cdks/cdk-rs-dfinity/multiply-dependency#update-interface-description-file) and remove the step where we delete the frontend canister from `dfx.json`

**Comment by sesi200** [comment]
The tutorial is still correct. We hope that this situation will be improved once dfx extensions land

**Comment by domwoe** [comment]
`dfx new --no-frontend` has no associated explanation in `dfx new` and doesn't work as expected (There should be no asset canister in `dfx.json` and no `src/xxx_frontend`.)  as @letmejustputthishere noted.
