### ISSUE TITLE
Blob return corrupted.

### ISSUE THREAD

**Issue by gabrielnic** [dfinity/sdk#2807]
Hi, not sure if this related to the sdk or motoko but please close it if it's not sdk related, with my apologies. 
One of my teammates reported that the blob he's uploading on return it's getting different values. 

The blob we're uploading is base64 encoded. 

I was able to reproduce this here: 
https://github.com/gabrielnic/dfinity-react/blob/blob_bug/src/App.tsx#L79
https://github.com/gabrielnic/dfinity-react/blob/blob_bug/src/test/main.mo#L30

Now the issue is this: 
The debug on line 35 prints this: 

`[Canister qvhpv-4qaaa-aaaaa-aaagq-cai] "\1F\8B\08\00\00\00\00\00\00\0A\8D\96\D9\6E\EA\48\10\86\EB\59\B8\9D\41\18\0C\06\8E\34\17\EC\10\B2\01\21\10\46\D1\51\D8\B7\04\9C\84\35\9A\77\9F\AF\EA\60\20\73\26\52\64\B9\DD\4B\2D\7F\FD\5D\5D\ED\0F\09\49\4F\16\3C\AF\D2\97\37\46\3F\E4\6F\09\4B\54\FE\3C\B4\8E\3C\D2\86\E4\5D\26\32\97\C1\51\26\24\1D\99\CA\AD\F8\72\23\29\89\49\52\0A\C8\3E\C9\03\BD\B8\6C\A5\25\97\52\95\AC\34\F8\66\90\56\1B\0B\71\4D\66\2C\23\69\CA\0E\D9\A6\3C\CB\0B\36\A6\B2\A6\1D\61\6B\2A\25\E6\36\07\8D\B0\DC\61\BB\84\BD\2C\56\D3\E8\34\25\C7\68\40\BB\64\9C\61\7C\05\8A\2B\74\7F\69\54\A5\8D\EF\05\7E\7B\C8\2D\F0\3E\A3\FF\84\EC\9C\7E\8B\D1\58\8A\D8\DF\49\ED\A0\D1\21\76\9F\D5\1E\18\8A\A0\F1\B0\39\90\15\9E\77\78\F1\B0\B2\05\69\0D\2F\01\AA\9A\94\B1\94\41\E6\09\79\97\A7\80\85\85\DC\83\A2\40\FC\53\B9\B6\D9\CB\23\AA\39\F8\13\8C\6E\41\1D\95\3C\7A\33\B4\CB\60\AD\61\A9\C8\77\0B\FF\7B\62\0D\B8\F2\59\29\C0\79\DB\A4\F6\60\9B\81\C7\63\EE\02\3E\EE\91\AE\81\D3\C3\56\A0\51\47\2E\63\3E\6A\30\98\93\21\EB\3E\16\7D\46\D7\A0\2B\63\6D\04\B6\E1\51\23\8B\C4\06\C6\C6\26\3B\02\51\01\64\15\F8\1A\82\76\88\ED\21\33\3B\D8\08\34\F2\78\E9\63\6B\02\E6\3B\F6\B2\0D\AA\67\66\B2\AC\B4\F0\3B\40\BB\02\BA\D6\91\2B\1F\4B\25\A2\5E\91\41\71\EC\29\BB\55\38\CA\23\BD\C3\E7\00\9E\92\D8\F9\79\E4\6A\67\8C\4C\C9\AA\1C\5C\4D\79\34\57\4A\EC\41\06\16\62\CC\17\F8\BE\9D\ED\87\CB\FA\1A\64\1D\BC\64\D0\9A\83\2C\C6\DC\0B\E8\36\A6\B5\85\B5\17\E2\0A\F6\7C\CA\DE\3C\83\E7\27\9E\FA\D8\EF\A1\51\42\E6\CA\72\74\8D\5C\5B\BA\E4\CC\E8\8C\AB\3E\7E\F7\30\D9\C2\52\9D\15\87\6C\75\D1\EA\62\65\81\C5\0D\D9\BA\C5\6A\10\C7\12\86\72\D8\F4\41\E1\A2\13\E7\AB\BB\E2\B3\13\1E\1E\8B\8C\76\D8\EF\1D\51\ED\88\77\6F\39\BA\25\3A\8F\7E\93\FD\48\32\DB\40\2B\07\E6\3B\C6\51\E4\03\54\05\BC\3B\CC\76\C0\B7\A0\7F\63\EC\76\F0\12\46\AA\01\4B\0F\D8\AA\81\3A\F0\F1\82\BF\3D\B6\12\C4\13\C7\8B\EE\79\18\CB\35\F4\AA\AC\96\EC\24\24\D0\0B\D8\DD\D8\39\18\C1\48\83\DD\BA\65\6D\C6\57\F3\68\82\ED\57\AC\A4\B0\EF\D8\6E\06\E7\BC\89\EC\CC\CE\A1\E6\6D\9D\77\82\ED\0E\B1\14\79\9A\F4\27\78\E8\1F\E3\B8\E7\F1\F1\10\E6\5B\21\9E\31\32\13\50\55\B0\9A\B0\2C\58\99\FC\F3\31\8E\2C\56\F3\CC\F7\60\E4\DE\32\B4\60\67\7A\85\97\27\D0\24\2C\F2\5B\3C\06\A8\D6\C8\E5\91\7C\01\41\19\4F\53\CB\F6\1C\F1\75\89\3C\63\DF\31\3E\46\C7\C8\57\20\F0\E0\B4\CB\F7\82\48\D3\D8\6D\30\DE\60\5D\4F\B0\07\07\57\8C\4F\B9\BB\21\E2\B4\65\44\0F\4F\0F\30\ED\E0\61\8F\CF\39\B2\35\CB\B7\18\5E\26\47\8D\19\33\51\3C\0D\C0\74\87\76\DF\F2\CA\41\5E\AB\97\0F\B3\09\2C\0E\AC\DE\04\B5\E4\06\2C\2E\33\6F\D8\8E\31\9E\31\53\B0\D3\97\B2\CA\EB\C1\93\EE\61\10\47\82\68\F7\BC\03\F4\AE\E0\AD\0B\BB\BA\37\2D\CE\A4\4B\EC\AF\56\B1\2F\79\4F\D5\67\09\8F\63\3B\35\51\DA\95\55\D1\35\5E\F4\6C\4D\D9\17\1F\1D\E5\3A\D0\88\61\BD\8D\57\AD\74\23\BC\3D\23\AB\55\3A\8B\E4\80\7E\03\5F\63\DB\29\8D\FC\F1\70\42\5E\41\B1\B4\7A\F8\CE\AB\37\CB\07\ED\13\91\BD\21\F9\7E\76\DB\AC\B0\AD\95\7D\4B\34\2D\AB\8C\7A\62\FB\CC\4F\E1\4D\F3\CA\83\C1\2C\52\01\22\0F\74\3F\8D\C7\81\E5\FA\D8\72\B4\01\86\22\ED\05\D6\93\48\14\F0\71\AA\23\4D\22\DB\D8\09\BF\44\AA\64\7E\7A\48\54\F8\5E\30\5F\67\BE\0D\63\9B\DF\62\68\58\04\EF\67\37\E4\C7\D9\6A\05\04\3A\1B\82\CD\24\7E\3C\DA\24\6D\9A\7E\DC\4E\50\9A\15\87\36\46\7C\CE\01\CF\89\87\40\DF\B1\F9\AD\F5\C3\E8\B9\76\47\6B\E5\38\CD\E8\78\7F\90\FE\87\D1\FF\E3\48\99\6E\1C\0C\7A\7B\3B\F4\B5\B2\26\68\15\9D\3E\0E\BD\AF\70\44\3F\E1\88\19\FA\73\1C\1A\4B\EA\9B\48\34\62\EF\C0\41\12\C9\B8\B1\A0\AF\CE\29\12\E5\E8\7B\48\12\BF\A1\70\BE\89\22\6A\0C\E8\9E\24\0C\C3\2F\24\3A\72\8D\09\D7\EE\94\AF\50\C4\3E\A1\70\C1\FD\99\8F\C4\61\7C\C2\F1\68\58\42\E8\9F\72\5F\F3\BC\8C\57\CD\B7\CC\7F\9E\1C\99\EE\92\E9\2B\72\B0\CA\A8\46\AE\67\C9\51\C7\AA\FC\CA\6E\2A\AD\E0\71\22\4B\C2\5E\04\8F\7D\B2\36\6F\FF\14\FA\67\72\8F\4E\87\95\06\56\D6\AC\E5\79\C6\C8\EA\6D\BB\B4\93\55\C0\F6\D7\EF\90\1A\30\A4\A2\A6\0C\C5\C0\F6\67\0B\A6\21\4F\87\5A\97\B2\BA\52\E3\D4\68\05\7F\23\D6\34\E7\68\83\A7\2A\72\7B\24\F3\96\5D\75\A4\96\D4\87\07\10\AA\BD\2D\67\54\6F\6B\FD\F7\EA\F2\5C\23\9B\B4\2A\A5\18\1F\EC\CE\6F\60\63\C6\D9\8B\E0\D9\41\67\81\8E\EE\58\04\BD\1D\D2\39\7C\E9\8D\A6\7F\8B\11\DB\AD\32\38\46\20\AC\A3\31\B7\2A\36\62\E5\16\6B\FA\DF\35\63\AC\3A\7A\7B\EB\ED\E6\DA\B9\8D\11\C7\04\A9\35\2B\7F\D8\6D\DC\20\03\94\C7\1E\3E\BA\F6\27\D8\67\65\61\7F\6A\7A\3B\64\ED\AE\EE\A3\E1\D9\DF\4D\84\36\43\8D\F5\8C\AB\C8\61\E7\82\3D\FC\8B\27\64\3B\FF\2F\7C\63\31\87\78\0B\00\00"`

I decoded the hex in decimals and compared to the one we upload and it's correct. 

But in console I get this: 

`gabriel@DESKTOP-8G906R5:~/projects/dfinity-react$ dfx canister call test getData "1"
(
  opt blob "\1f\8b\08\00\00\00\00\00\00\0a\8d\96\d9n\eaH\10\86\ebY\b8\9dA\18\0c\06\8e4\17\ec\10\b2\01!\10F\d1Q\d8\b7\04\9c\845\9aw\9f\af\ea\60 s&Rd\b9\ddK-\7f\fd]]\ed\0f\09IO\16<\af\d2\977F?\e4o\09KT\fe<\b4\8e<\d2\86\e4]&2\97\c1Q&$\1d\99\ca\ad\f8r#)\89IR\0a\c8>\c9\03\bd\b8l\a5%\97R\95\ac4\f8f\90V\1b\0bqMf,#i\ca\0e\d9\a6<\cb\0b6\a6\b2\a6\1dak*%\e66\07\8d\b0\dca\bb\84\bd,V\d3\e84%\c7h@\bbd\9ca|\05\8a+t\7fiT\a5\8d\ef\05~{\c8-\f0>\a3\ff\84\ec\9c~\8b\d1X\8a\d8\dfI\ed\a0\d1!v\9f\d5\1e\18\8a\a0\f1\b09\90\15\9ewx\f1\b0\b2\05i\0d/\01\aa\9a\94\b1\94A\e6\09y\97\a7\80\85\85\dc\83\a2@\fcS\b9\b6\d9\cb#\aa9\f8\13\8cnA\1d\95<z3\b4\cb\60\ada\a9\c8w\0b\ff{b\0d\b8\f2Y)\c0y\db\a4\f6\60\9b\81\c7c\ee\02>\ee\91\ae\81\d3\c3V\a0QG.c>j0\98\93!\eb>\16}F\d7\a0+cm\04\b6\e1Q#\8b\c4\06\c6\c6&;\02Q\01d\15\f8\1a\82v\88\ed!3;\d8\084\f2x\e9ck\02\e6;\f6\b2\0d\aagf\b2\ac\b4\f0;@\bb\02\ba\d6\91+\1fK%\a2^\91Aq\ec)\bbU8\ca#\bd\c3\e7\00\9e\92\d8\f9y\e4jg\8cL\c9\aa\1c\5cMy4WJ\ecA\06\16b\cc\17\f8\be\9d\ed\87\cb\fa\1ad\1d\bcd\d0\9a\83,\c6\dc\0b\e86\a6\b5\85\b5\17\e2\0a\f6|\ca\de<\83\e7\27\9e\fa\d8\ef\a1QB\e6\cart\8d\5c[\ba\e4\cc\e8\8c\ab>~\f70\d9\c2R\9d\15\87lu\d1\eabe\81\c5\0d\d9\ba\c5j\10\c7\12\86r\d8\f4A\e1\a2\13\e7\ab\bb\e2\b3\13\1e\1e\8b\8cv\d8\ef\1dQ\ed\88wo9\ba%:\8f~\93\fdH2\db@+\07\e6;\c6Q\e4\03T\05\bc;\ccv\c0\b7\a0\7fc\ecv\f0\12F\aa\01K\0f\d8\aa\81:\f0\f1\82\bf=\b6\12\c4\13\c7\8b\eey\18\cb5\f4\aa\ac\96\ec$$\d0\0b\d8\dd\d89\18\c1H\83\dd\baem\c6W\f3h\82\edW\ac\a4\b0\ef\d8n\06\e7\bc\89\ec\cc\ce\a1\e6m\9dw\82\ed\0e\b1\14y\9a\f4\27x\e8\1f\e3\b8\e7\f1\f1\10\e6[!\9e12\13PU\b0\9a\b0,X\99\fc\f31\8e,V\f3\cc\f7\60\e4\de2\b4\60gz\85\97\27\d0$,\f2[<\06\a8\d6\c8\e5\91|\01A\19OS\cb\f6\1c\f1u\89<c\df1>F\c7\c8W \f0\e0\b4\cb\f7\82H\d3\d8m0\de\60]O\b0\07\07W\8cO\b9\bb!\e2\b4eD\0fO\0f0\ed\e0a\8f\cf9\b25\cb\b7\18^&G\8d\193Q<\0d\c0t\87v\df\f2\caA^\ab\97\0f\b3\09,\0e\ac\de\04\b5\e4\06,.3o\d8\8e1\9e1S\b0\d3\97\b2\ca\eb\c1\93\eea\10G\82h\f7\bc\03\f4\ae\e0\ad\0b\bb\ba7-\ce\a4K\ec\afV\b1/yO\d5g\09\8fc;5Q\da\95U\d15^\f4lM\d9\17\1f\1d\e5:\d0\88a\bd\8dW\adt#\bc=#\abU:\8b\e4\80~\03_c\db)\8d\fc\f1pB^A\b1\b4z\f8\ce\ab7\cb\07\ed\13\91\bd!\f9~v\db\ac\b0\ad\95}K4-\ab\8czb\fb\ccO\e1M\f3\ca\83\c1,R\01\22\0ft?\8d\c7\81\e5\fa\d8r\b4\01\86\22\ed\05\d6\93H\14\f0q\aa#M\22\db\d8\09\bfD\aad~zHT\f8^0_g\be\0dc\9b\dfbhX\04\efg7\e4\c7\d9j\05\04:\1b\82\cd$~<\da$m\9a~\dcNP\9a\15\876F|\ce\01\cf\89\87@\df\b1\f9\ad\f5\c3\e8\b9vGk\e58\cd\e8x\7f\90\fe\87\d1\ff\e3H\99n\1c\0cz{;\f4\b5\b2&h\15\9d>\0e\bd\afpD?\e1\88\19\fas\1c\1aK\ea\9bH4b\ef\c0A\12\c9\b8\b1\a0\af\ce)\12\e5\e8{H\12\bf\a1p\be\89\22j\0c\e8\9e$\0c\c3/$:r\8d\09\d7\ee\94\afP\c4>\a1p\c1\fd\99\8f\c4a|\c2\f1hXB\e8\9fr_\f3\bc\8cW\cd\b7\cc\7f\9e\1c\99\ee\92\e9+r\b0\ca\a8F\aeg\c9Q\c7\aa\fc\can*\ad\e0q\22K\c2^\04\8f}\b26o\ff\14\fagr\8fN\87\95\06V\d6\ac\e5y\c6\c8\eam\bb\b4\93U\c0\f6\d7\ef\90\1a0\a4\a2\a6\0c\c5\c0\f6g\0b\a6!O\87Z\97\b2\baR\e3\d4h\05\7f#\d64\e7h\83\a7*r{$\f3\96]u\a4\96\d4\87\07\10\aa\bd-gTok\fd\f7\ea\f2\5c#\9b\b4*\a5\18\1f\ec\ceo\60c\c6\d9\8b\e0\d9Ag\81\8e\eeX\04\bd\1d\d29|\e9\8d\a6\7f\8b\11\db\ad28F \ac\a31\b7*6b\e5\16k\fa\df5c\ac:z{\eb\ed\e6\da\b9\8d\11\c7\04\a95+\7f\d8m\dc \03\94\c7\1e>\ba\f6\27\d8gea\7fjz;d\ed\ae\ee\a3\e1\d9\dfM\846C\8d\f5\8c\ab\c8a\e7\82=\fc\8b\27d;\ff/|c1\87x\0b\00\00",
)`

Initially I thought it's just my bash but in unity we're getting the same corrupted values. 

The thing is if I do the same call in JS using the agent-js I get the correct values. 

I even tried to return Blob.toArray but instead of getting a [Nat8] I still get the exact same value as above for some reason. 

### Meta

`dfx --version`:
```
0.12.1
```

**Comment by filharvey** [comment]
The Unity agent is this one. 

[Unity Agent](https://github.com/ShikuLabs/agent-unity)

It uses the Rust-Agent in a dll to connect to the canisters.

**Comment by sesi200** [comment]
Is the data different or the representation? Blobs get rendered differently than `[Nat8]`, which is the internal Motoko representation of blobs. My first suspicion is that it's a matter of displaying the values, not the values being different.

**Comment by gabrielnic** [comment]
Hey Severin, that was my initial thought but we're getting the same weird values in unity as well. So it's not just a matter of displaying the values.

**Comment by filharvey** [comment]
Thanks, I have confirmed that is the case and the data does match once I convert back to all Hex based data. @gabrielnic we can close this issue.
