### ISSUE TITLE
Candid file check failed: Cannot import

### ISSUE THREAD

**Issue by paulyoung** [dfinity/sdk#2874]
I recently started breaking up my Candid file into smaller files to make it more manageable.

For example, I moved everything related to Canistergeek to `candid/canistergeek.did` and now do `import "canistergeek.did";` in `candid/codebase.did`.

My `candid_interface_compatibility` test (similar to [this one](https://github.com/dfinity/sdk/blob/89b4bd9ae0961089790c4982dcbb8461026c6bdb/src/canisters/frontend/ic-certified-assets/src/lib.rs#L288-L306)) supports this, and now also my `ic-repl` tests (thanks to @chenyan2002 and https://github.com/chenyan2002/ic-repl/pull/50)

However, `dfx generate` now fails.

I tried the following:

1. `dfx generate --verbose codebase_backend`

I expected to see this happen:

```
Generating type declarations for canister codebase_backend:
  frontend/declarations/codebase_backend/codebase_backend.did.js
```

Instead, this happened:

```
Error: (BFailed while trying to generate type declarations for 'codebase_backend'.
Caused by: (BFailed while trying to generate type declarations for 'codebase_backend'.
  Candid file check failed for frontend/declarations/codebase_backend/codebase_backend.did.
    Cannot import "canistergeek.did"
```

https://github.com/dfinity/sdk/blob/fc6d58955d02ba38e123159096c1df9e972757ce/src/dfx/src/util/mod.rs#L144-L152

### Meta

`dfx --version`:
```
dfx 0.12.0-beta.3
```

**Comment by sesi200** [comment]
@chenyan-dfinity Is this something that we can fix by upgrading Motoko?
