### ISSUE TITLE
vscode gives false warning in json schema

### ISSUE THREAD

**Issue by ocluf** [dfinity/sdk#2908]
Ik have the following prebuild canister configuration in vscode:

"Token": {
      "type": "custom",
      "wasm": "ledger/ic-icrc1-ledger.wasm",
      "candid": "ledger/icrc1.did"
}

Warning given in the json file (with the yellow squiggly line under "Token") 

Missing property "build". The canister seems to deploy fine and does not need the "build" field in the config

**Comment by rvanasa** [comment]
Transferring to the [dfinity/sdk](https://github.com/dfinity/sdk) repository, since the `dfx.json` schema directly uses this file:

https://github.com/dfinity/sdk/blob/master/docs/dfx-json-schema.json

**Comment by sesi200** [comment]
Thank you for reporting this, @ocluf. I added an [item](https://dfinity.atlassian.net/browse/SDK-932) to our backlog, but I won't make any promises as to when we'll get around to fixing this.
