### ISSUE TITLE
headers not updated

### ISSUE THREAD

**Issue by snodnipper** [dfinity/sdk#3053]
Creating a demo project, I wanted to update the headers, specifically the Content-Security-Policy in `.ic-assets.json5`.

Ultimately (after small changes not working), I changed:

`"Content-Security-Policy": "default-src 'self';script-src 'self' 'unsafe-eval';connect-src 'self' https://ic0.app https://*.ic0.app;img-src 'self' data:;style-src * 'unsafe-inline';style-src-elem * 'unsafe-inline';font-src *;object-src 'none';base-uri 'self';frame-ancestors 'none';form-action 'self';upgrade-insecure-requests;",`

to

"Content-Security-Policy": "",

I expected 
`dfx build;dfx deploy --network ic --no-wallet`
to ensure that those headers were updated.  They were not as verified by:

`curl -v https://xxxx-xxxx-xxxx-xxxx-xxx.ic0.app/myresource.html`

### Resolution ###
I could resolve the problem by executing:
`dfx canister uninstall-code xxxxx-xxxxx-xxxxx-xxxxx-xxx --network ic`
`dfx build;dfx deploy --network ic --no-wallet`

### Meta

`dfx --version`:
```
dfx 0.13.1
```

**Comment by sesi200** [comment]
Thanks for reporting. This is a known limitation, and @smallstepman has plans to implement CRUD methods for asset metadata.

Currently, asset metadata (like headers, content_type, max_age, enable_aliasing, basically everything in `CreateAssetArguments`) can only be set on asset creation. Workaround, as you already figured out, is to reinstall the canister or delete and re-upload the assets.

Note to self: [internal ticket](https://dfinity.atlassian.net/browse/SDK-567)

**Comment by smallstepman** [comment]
One more way to do it is to call the `set_asset_properties` method manually (without the "`assert_command`"): https://github.com/dfinity/sdk/blob/26aa509d97f388d48442e0f5626b6d19b0ee0658/e2e/tests-dfx/assetscanister.bash#L1188
There are more examples in that file if you're interested. It doesn't require redeploying the assets, but you'd need to cover each asset one by one.
