### ISSUE TITLE
Deploy not working on v14.1 (neither on v14.0)

### ISSUE THREAD

**Issue by tiagol89** [dfinity/sdk#3178]
I tried the following:

1. dfx deploy --network staging (which is same as IC)

I expected to see this happen: to deploy with success

Instead, this happened: it gave error, informing of user not controller, but that is false.

Context:
This is a canister created around dfx ~0.12, that is around Jan/Feb of 2023.
I have seen this issue in the past:
https://forum.dfinity.org/t/canisters-controllers-error-in-deployment/6337/12

And at the time (some months ago, v0.13.1) I had already upgrade all my wallets in all envs/networks. Issue was solved.
(and a good indication of that is that the controllers of the canister is exactly the Principal and it's Wallet).

So, both ids have access to it, and since I moved from dfx 0.13.1 to 0.14.1 (today), it happened this error.

Attempts I did to fix (but none had any effect on the error):
- Tried to upgrade again the wallet, it upgrades fine.
- Tried calling with --no-wallet, and --wallet.
- Deposited more cycles.
- Tried setting dfx.json to v0.14.0 (it informs that is calling from that version, but same output).
- Tried setting dfx.json to v0.13.1 (but it informs it has incompatible cache and does not even attempt).

I did not try to uninstall and install at v0.13.1 (I suspect that it would work, as it was working fine, some 2 weeks ago).

An important note, this is only happening on this "NFT" / "motoko" canister. It's not happening on another canister I have, created at the same date, same "env"/"network", that is frontend/backend (assets canister). The assets one is deploying fine.

I suspect it's something on the wallet, but am not seeing how to "upgrade" / "fix it" to correctly see the ids.

Canister behaving wrong (NFT / Motoko): bhuj6-gaaaa-aaaan-qc7ba-cai
Canister behaving well (Assets Canister / Motoko):  bjwew-5qaaa-aaaan-qc7aa-cai
Principal (calling and controller): 4e6g2-eoooo-h2lec-3h725-hvmmc-fvgsd-qakd3-qsj44-6dlaw-p5ngz-mae
Wallet of that principal: 5j2kx-iqaaa-aaaan-qc25q-cai

Proofs:
![Screenshot 2023-06-18 at 14 28 52](https://github.com/dfinity/sdk/assets/19423709/fedcc066-af9f-4797-ad1b-fa125b507d3a)

![Screenshot 2023-06-18 at 20 15 13](https://github.com/dfinity/sdk/assets/19423709/879a724f-f86f-4413-a07c-2c6a24863785)

### Meta

`dfx --version`: 
```
0.14.1
```

<details><summary>Further log output</summary>
<p>

```
Please enter the passphrase for your identity: [hidden]
Decryption complete.
Deploying all canisters.
All canisters have already been created.
Building canisters...
Installing canisters...
Creating UI canister on the staging network.
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed while trying to install all canisters.
    Failed to install wasm module to canister 'obsidian_tears_nft'.
      Failed to install candid UI canister.
        Create canister call failed.
          The replica returned an HTTP Error: Http Error: status 403 Forbidden, content type "text/plain", content: Caller 4e6g2-eoooo-h2lec-3h725-hvmmc-fvgsd-qakd3-qsj44-6dlaw-p5ngz-mae is not allowed to call ic00 method provisional_create_canister_with_cycles
Error explanation:
Each canister has a set of controllers. Only those controllers have access to the canister's management functions (like install_code or stop_canister).
The principal you are using to call a management function is not part of the controllers.
How to resolve the error:
To make the management function call succeed, you have to make sure the principal that calls the function is a controller.
To see the current controllers of a canister, use the 'dfx canister info (--network ic)' command.
To figure out which principal is calling the management function, look at the command you entered:
    If you used '--wallet <wallet id>', then the wallet's principal (the '<wallet id>') is calling the function.
    If you used '--no-wallet' or none of the flags, then your own principal is calling the function. You can see your own principal by running 'dfx identity get-principal'.
To add a principal to the list of controllers, one of the existing controllers has to add the new principal. The base command to do this is 'dfx canister update-settings --add-controller <controller principal to add> <canister id/name or --all> (--network ic)'.
If your wallet is a controller, but not your own principal, then you have to make your wallet perform the call by adding '--wallet <your wallet id>' to the command.

The most common way this error is solved is by running 'dfx canister update-settings --network ic --wallet "$(dfx identity get-wallet)" --all --add-controller "$(dfx identity get-principal)"'.
```

</p>
</details>

**Comment by sesi200** [comment]
Can you show the network definition? I suspect `dfx` erroneously fails to notice this is mainnet, and therefore attempts to run functions that are not available on mainnet

**Comment by tiagol89** [comment]
Hi @sesi200 , great intuition, it was indeed the network definition on dfx.json:
![Screenshot 2023-06-19 at 21 05 36](https://github.com/dfinity/sdk/assets/19423709/77325942-a780-41a9-a7ea-88a2748713ad)

In the past I must have updated on the assets one, and not on the NFT one, thanks so much for helping to spot this out!
