### ISSUE TITLE
dfx crashed under a race condition

### ISSUE THREAD

**Issue by vporton** [dfinity/sdk#3279]
I tried the following:

I ran DFX under load of 10 "threads" of execution (started by `await` from one canister, stress-testing another canister).

Usually it runs well, but once it crashed.

I expected to see this happen: The process to run to the end without a crash.

Instead, this happened:
```
$ dfx start --clean
...
2023-08-03 15:37:57.064549712 UTC: [Canister be2us-64aaa-aaaaa-qaabq-cai] STARTING STRESS TEST: 10 threads, each 1_000 steps
thread 'MR Batch Processor' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:708:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
version: 0.8.1
 Aug 03 15:40:48.757 WARN Internal Error during request:
hyper::Error(
    Io,
    Os {
        code: 104,
        kind: ConnectionReset,
        message: "Connection reset by peer",
    },
)
Stopping icx-proxy...
Stopped.
Initialized replica.
Dashboard: http://localhost:34525/_/dashboard
2023-08-03 15:43:07.059130058 UTC: [Canister be2us-64aaa-aaaaa-qaabq-cai] Number of partition canisters: 615
```

### Meta

`dfx --version`:
```
dfx 0.14.3
```

**Comment by vporton** [comment]
The issue is fairly reproducible: For [this commit](https://github.com/vporton/NacDB/tree/66aea3d524a7adf5ee67086133258bf222bbaa50) it is reproducible for like about 1/2 of runs.

To reproduce the issue run in `stress-test/` `make` several times and get errors like:

```
$ dfx start --clean
Running dfx start for version 0.14.3
Using the default definition for the 'local' shared network because /home/porton/.config/dfx/networks.json does not exist.
Initialized replica.
Dashboard: http://localhost:36243/_/dashboard
...
thread 'MR Batch Processor' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:708:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
version: 0.8.1
 Aug 03 20:04:19.626 WARN Internal Error during request:
hyper::Error(
    Connect,
    ConnectError(
        "tcp connect error",
        Os {
            code: 111,
            kind: ConnectionRefused,
            message: "Connection refused",
        },
    ),
)
Stopping icx-proxy...
Stopped.
2023-08-03 20:02:14.380126363 UTC: [Canister bkyz2-fmaaa-aaaaa-qaaaq-cai] STARTING STRESS TEST: 10 threads, each 1_000 steps
Initialized replica.
Dashboard: http://localhost:43799/_/dashboard
```

**Comment by vporton** [comment]
Please remove this bug report, because it affects Replica, not DFX, and therefore is a security vulnerability, that I will report in another way.

**Comment by vporton** [comment]
I applied for a DFINITY grant with the task to fix this bug.

**Comment by sesi200** [comment]
Thanks for reporting this! From internal discussions:

>It looks like we try to spawn a new thread (normal), but fail (not normal). There doesn't appear to be a good way to catch such errors, given that it's just an expect in the standard library.
We are possibly running into some maximum number of allowed threads, which is set by the OS in some way. This would explain why it happens in dfx only, where we run on the user's OS, but not in production where we control such limits ourselves.

Since, as you said, it's a replica thing and not a dfx issue I'll close this discussion
