### ISSUE TITLE
download https://github.com/dfinity/sdk/releases/download//dfx--x86_64-darwin.tar.gz  404

### ISSUE THREAD

**Issue by JSjump** [dfinity/sdk#3494]
I tried the following:

1.sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

this happened: 
1.[ *explanation*](curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 11 ms: Couldn't connect to server)
2.curl: (22) The requested URL returned error: 404
dfinity-sdk: command failed: downloader https://github.com/dfinity/sdk/releases/download//dfx--x86_64-darwin.tar.gz

**Comment by sesi200** [comment]
It looks like you can't connect to `raw.githubusercontent.com`. This usually happens if either your connection is unstable or if your ISP blocks access. Can you try using a VPN?

**Comment by JSjump** [comment]
> It looks like you can't connect to `raw.githubusercontent.com`. This usually happens if either your connection is unstable or if your ISP blocks access. Can you try using a VPN?

Thank you for your reply and suggestions. The issue has been resolved by downloading the DFINITY SDK from GitHub Releases.
