### ISSUE TITLE
A developer can manage third-party libraries

### ISSUE THREAD

**Issue by ghost** [dfinity/sdk#479]
To consider:

**A Motoko Package Manager**: Can pull in packages written in Motoko to be imported by your app, which is also written in Motoko. You could then compile your app into WebAssembly and install it as a canister. This approach makes Motoko a first class language like Node or Rust.

**An Internet Computer Package Manager**: Can pull in WebAssembly modules written in ANY language to be linked by your app, also written in ANY language and compiled to WebAssembly. This approach make Motoko less important but creates a flourishing ecosystem around developing for the Internet Computer itself.

**A Canister Package Manager**: Can pull in references to IC Canisters running on the Internet Computer. Developers could create a canister, deploy it, and allow it to be called by other canisters for payment. This approach gives Open Source software developers a business model based in how useful their software is, potentially changing the face of tech as we know it.

Some of these strategies should live in SDK, others with the Languages team.

**Comment by sesi200** [comment]
Too large for a single issue. Vessel already exists, canister package manager or similar things are under discussion
