### ISSUE TITLE
`dfx new` should warn if missing dependencies (e.g. Node)

### ISSUE THREAD

**Issue by ghost** [dfinity/sdk#753]
From Tungsten Hackathon:

> "dfx new hello" fails (as reported in slack) , "npm install node" fixed the issue (thnx Dimitris)

> We had some fun with `npm install` not working out of the box because npm install needs code generated by the build but the build depends on react, so there is a chicken and egg problem.  Manually installing webpack solves this but maybe there is a better way of handing this.

**Comment by sesi200** [comment]
handled at some point in the past
