### ISSUE TITLE
`dfx build` should warn on missing dependencies (e.g. `node_modules`)

### ISSUE THREAD

**Issue by ghost** [dfinity/sdk#756]
From Tungsten Hackathon:

> dfx build can fail with NotFound. No further information is displayed. No idea what dfx couldn't find. After a (long) time I realized I need to run npm install and it was probably webpack

> Diego had some errors which magically went away with "npm install." I have no idea why... and i only thought of npm install because someone told me. Since thiis not a node.js project in my mind, i would not have thought of that.

**Comment by sesi200** [comment]
Error messages are useful now
