### ISSUE TITLE
Design: Implement telemetry for SDK

### ISSUE THREAD

**Issue by alexabsmith** [dfinity/sdk#881]
- [ ] Define what we would like to track
- [ ] Research existing tools
- [ ] Provide recommendation
- [ ] Work with legal on relevant license agreement update(s)

[Braindump working doc](https://docs.google.com/document/d/18uBJMMSHkIYGPZ9R81eYq75ymoEB04XW5mUjyGwhoYk/edit?usp=sharing)
#838

**Comment by sesi200** [comment]
Is now tracked in [SDK-500](https://dfinity.atlassian.net/browse/SDK-500)
